services:
  - type: web
    name: geotiff-server
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y gdal-bin poppler-utils && pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
